### ISSUE TITLE
Safari:DemoWebsite - Icon background gradient issue

### ISSUE THREAD

**Issue by Perry-chouteau** [lunapark/lunapark#2]
Safari=Version 17.4.1
The animation is laggy with a vertical line, the gif isn't purely showing what I'm really watching, cause I'm continuously seeing the vertical line.
![CleanShot 2024-07-16 at 14 00 43](https://github.com/user-attachments/assets/ad37973b-191e-4ffb-bb29-cbc10db9c88d)

**Comment by Perry-chouteau** [comment]
It happens on most icons of the website:
![CleanShot 2024-07-16 at 14 08 46](https://github.com/user-attachments/assets/cb29106f-4a75-4dde-bb8f-c704fdf2cb8a)

**Comment by hugoattal** [comment]
Thanks for reporting this! It seems to be a problem with safari handling of `filter: drop-shadow`

cf https://github.com/mdn/browser-compat-data/issues/17726

I'll try a few solutions to mitigate the issue, I'll keep you posted!

**Comment by hugoattal** [comment]
This should be fixed 🥳! Could you confirm?
